title: "Hunting Things"
description: "Threat Hunting things..."
baseurl: ""
url: "https://naotaclone.github.io"
theme: null
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
collections:
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md